### ISSUE TITLE
Refactoring To-do list

### ISSUE THREAD

**Issue by TrentonBush** [deployment-gap-model-education-fund/deployment-gap-model#138]

**Comment by TrentonBush** [comment]
- [ ] #206 
- [ ] #166 
- [ ] move PAD-US analysis inside repo instead of storing results as a flat file. The only reason it is arranged as such is that we didn't have a cloud data cache set up at the time and the input data was too large for git.
- [ ] move Energy Communities analysis inside repo, if the dependencies can be reasonably resolved. I suspect this project has been abandoned by RMI, so I don't expect to lose access to future updates.
- [ ] cache pudl MCOE calculation. It takes over half the total run time and never changes.
- [ ] update db writes to use COPY instead of shockingly slow INSERT. In combination with the above, this would drop run time from ~4 minutes to tens of seconds. This is a qualitative step change from "run it and get a drink" to an interactive process. Interactivity allows for more experimentation and error checking due to the reduced costs of experiments.

**Comment by bendnorman** [comment]
These sub issues have been handled, no longer relevant or broken out into new issues.
