### ISSUE TITLE
Tableau MVP

### ISSUE THREAD

**Issue by TrentonBush** [deployment-gap-model-education-fund/deployment-gap-model#2]
### Description
This Epic covers setup and demonstration of the bare minimum Tableau functionality needed to make a county-level map that the client can see.

### Motivation
The ultimate deliverable of the DBCP is a set of dashboards and analysis tools that generate and disseminate actionable insights. But first we need to get Tableau working!

### Scope
Finish line: a choropleth map of some county-level metric (doesn't matter what) that Matt can see.
This includes:
- [x] Tableau Online account creation
- [x] billing Matt's procurement card and possibly transferring ownership
- [x] uploading a csv of county-level data
- [x] doing whatever needs to be done to share it

Out of scope
* making a *useful* or *beautiful* dashboard
