### ISSUE TITLE
Create automation to update airtable data in c3 repo

### ISSUE THREAD

**Issue by bendnorman** [deployment-gap-model-education-fund/deployment-gap-model#365]
Create a script that archives Airtable data using pyairtable.

The structure of the GCS bucket:

```
dgm-archive/
- gridstatus/
- ballotready/
- airtable/
   - {base_name}/
       - schema.json
       - {table_name_1}.json
       - {table_name_2}.json
   - ...
- ...
```

We'll use GCS object versioning for now and attach some metadata to objects. We'll save the schema generation number as metadata for the table objects so we know which version of the schema file they refer to.

**Success criteria**: create a github action that archives the data, runs the ETL and publishes it to GCS and BQ

## TODO
- [x] Create abstract archiver
- [x] create Airtable arcivher
- [x] create a script that collects all the archives and archives the data!
- [x] create a github action that archives the data, runs the ETL and publishes it to GCS and BQ
- [ ] Write up documentation on how to update data
- [ ] make sure the update-data action triggers are correct before merging in. [Add `paths-ignore: src/dbcp/settings.yaml`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-excluding-paths) so the CI won't run immediately after the data is updated?
- [ ] Remove testing logic in 'Publish publish outputs' step
- [ ] Merge just the github action file into main so the schedule kicks off on dev
- [x] clean up the publish script a bit
- [x] Why aren't logs being emitted for cli commands?
- [x] Figure out how to handle the empty column issues with airtable archiver
- [ ] Add some tests!
- [x] Add proper entry point for cli.py command: decided not to do this because we're not actually installing dbcp as package

## Nice to haves
- [ ] The airtable API does not return a column if the value is empty for a record. This is a problem if the column of a table is completely null. However, the columns are all listed in the schema.json. We could figure out how to incorporate the schema.json into the extraction process so we can construct a dataframe that includes empty columns. I think the base schema has all the columns, even the ones that are hidden. How can we figure out which ones are in the view? We should treat the view columns as what CP users expect.
- [ ] Incorporate schema.json into the extraction process so we can infer datatypes. The API allows us to pull all record values in as string and not have to deal with linking records across tables or maintain the datatypes but have to look up table values. Right now we are just pulling everything as a string because it's simpler and we already have a column name to datatype mapping set up.

**Comment by jdangerx** [comment]
@bendnorman thanks for adding notes here!

re: success criteria, I'm assuming this is done when:
* [ ] we have a script that you can run manually, with some sort of auth env var set
* [ ] the script grabs data from all airtable tables and puts it into GCS according to the structure above

What goes into `schema.json`? Will that be manually populated or does the script need to generate that too?

**Comment by bendnorman** [comment]
I expanded the scope of this issue to be the whole airtable automation project. [Phase I in the design doc](https://docs.google.com/document/d/111g3fYXHzP77Ezdq_bBXfOr_7Cjvw06BK8WImc2Zi2Q/edit#heading=h.ldp8xoltggkv). I also added success criteria.

I'm grabbing the schema.json file from the Airtable API.

**Comment by bendnorman** [comment]
#366
