### ISSUE TITLE
Data Integration

### ISSUE THREAD

**Issue by TrentonBush** [deployment-gap-model-education-fund/deployment-gap-model#4]
### Description
Minimum ETL for the 9-ish initial datasets.

### Scope
This is a bare-bones ETL - just moving the data from a flat file to a database with just enough transformation and enrichment to enable county-level aggregation. There will be flaws but we won't fix them until later.
NOTE: the following list may be out of date. Check the project management docs
- [x] EIP Fossil Infra Projects
- [x] LBNL ISO Interconnection Queue
- [ ] EPA EJ Screen
- [x] PUDL power plants
- [ ] Oil and Gas wells
- [x] NCSL Local Permitting
- [ ] EIA Muni and Co-Ops
- [ ] Census county shapefile (necessary?)
- [x] New Dataset X

#### Out of Scope:
* complex data cleaning
* missing data imputation
* entity resolution
* resolving inconsistencies between data sources
* automated scraping or archiving
